name: Build APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-alpha:
    runs-on: ubuntu-latest
    environment: alpha
    needs:
      - build
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Delete alpha release using GitHub CLI
        run: |
          if gh release view alpha; then
            gh release delete alpha --yes
          else
            echo "No alpha release exists."
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: alpha
          name: 'Alpha'
          body: |
            1
            2
            3

            此版本为新架构测试版，请提前加入内测群 1020036141 了解详情
          prerelease: true
          files: |
            FzuHelper_7.1.8.718524.apk
        env:
          GITHUB_TOKEN: ${{ github.token }}
